name: "Run eventing-github e2e tests"
on:
  workflow_dispatch:
jobs:
  e2e-testing:
    name: GitHubSource Test
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: kind.local
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout eventing-github
        uses: actions/checkout@v2
        with:
          repository: knative-sandbox/eventing-github
          path: eventing-github
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install ko
        run: |
          GO111MODULE=on go get github.com/google/ko/cmd/ko@master
      - name: Setup kind
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: "v0.9.0"
      - name: Setup cluster
        run: |
          cd main
          go test -v ./test/eventing-github/... -setup=true
      - name: Run Tests
        run: |
          cd main
          go test -v ./test/eventing-github/...

